"""add_gender_ Column

Revision ID: 42501683ffee
Revises: d93e28df21f4
Create Date: 2022-11-10 11:46:08.623097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42501683ffee'
down_revision = 'd93e28df21f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('gender', sa.String(length=1), nullable=True))
    op.execute("update employee set gender='M' where id in(1,3);")
    op.execute("update employee set gender='F' where id in(2);")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'gender')
    # ### end Alembic commands ###
