"""add_email_Column

Revision ID: b659326f13b9
Revises: 42501683ffee
Create Date: 2022-11-10 11:58:50.264838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b659326f13b9'
down_revision = '42501683ffee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('email_id', sa.String(), nullable=True))
    op.execute("update employee set email_id='ravin@kaigal.com' where id=1;")
    op.execute("update employee set email_id='geetha@kaigal.com' where id=2;")
    op.execute("update employee set email_id='chandu@kaigal.com' where id=3;")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'email_id')
    # ### end Alembic commands ###
