"""bulk insert

Revision ID: d93e28df21f4
Revises: c36ca451b963
Create Date: 2022-11-10 11:01:57.214457

"""
from datetime import date

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Integer, column, String, table

# revision identifiers, used by Alembic.
revision = 'd93e28df21f4'
down_revision = 'c36ca451b963'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    employee_table=table('employee',
                         column('id', Integer),
                         column('name', String),
                         column('yob', Integer)
                         )

    op.bulk_insert(employee_table,
                   [
                       {'id': 1, 'name': 'Ravin',
                        'yob': 2010},
                       {'id': 2, 'name': 'Geetha',
                        'yob': 2002},
                       {'id': 3, 'name': 'Chandu',
                        'yob': 2002},
                   ]
                   )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("truncate table employee;")
    # ### end Alembic commands ###
